# Generated by Django 4.2 on 2023-05-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S3Image',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('c_date', models.DateTimeField(blank=True, null=True)),
                ('img_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
