# Generated by Django 4.2 on 2023-05-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detect',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('cam_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('c_date', models.DateTimeField()),
                ('img_url', models.CharField(max_length=200)),
                ('distance', models.FloatField(default=0)),
                ('area', models.FloatField(default=0)),
            ],
        ),
    ]
